### ISSUE TITLE
Cancelled projects showing up again upon page refresh - rebuild issue?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#775]
On giveth.io, I noticed that on the projects page a project I *knew* was cancelled (Giveeth) was showing up near the top again:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/372d8f5a-fcb5-4e30-bae4-467c64bda08e)

And then after about 10s it disappears:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3723d5a0-7319-45d7-b7a4-1773245f6fbf)

If I click on the project page before it disappears, I can also go directly to its page and everything looks normal:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/83c4f956-e1b1-463e-9bf2-84e16e3c890a)

until 10s or so passes and I get:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e6d95387-ae4a-4417-ab98-1656943610ac)

**Comment by positonic** [comment]
This is resolved, on dev and will go to staging soon.

**Comment by positonic** [comment]
https://github.com/Giveth/impact-graph/pull/62

**Comment by divine-comedian** [comment]
@jamespfarrell 
Testing on Giveth.io 
Brave browser clean cache and cookies.
Do you have any information for how we can test this on staging? I notice Giveeth is still showing up briefly on the projects page as Lauren described.

![image](https://user-images.githubusercontent.com/67759413/119265914-98630400-bbb6-11eb-8100-20aa40f2d23f.png)

**Comment by laurenluz** [comment]
issue moved to next: https://github.com/Giveth/giveth-next/issues/31
